# 產生自以下指令
# kubectl create configmap nginx-configmap --from-file=./nginx/nginx.conf -o yaml --dry-run=client >> -configmap.yaml
---
apiVersion: v1
data:
  nginx.conf: |
    server {
        listen 80;
        index index.php index.html;
        access_log /var/log/nginx/access.log ;
        error_log /var/log/nginx/error.log ;
        root /usr/share/nginx/html ;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php-service:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        location / {
            try_files $uri $uri/ /index.php?$query_string;
            gzip_static on;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-configmap
