---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest  
        ports:
        - containerPort: 80  
      #
      #   volumeMounts:
      #   - name: nginx-volume
      #     readOnly: true
      #     mountPath: /etc/nginx/conf.d
      # volumes:
      # - name: nginx-volume
      #   configMap:
      #     name: nginx-configmap
