name: deploy-argocd
on:
  workflow_call:
    secrets:
      MY_GITHUB_PRIVATE_KEY:
        required: true
      
jobs:
  argocd:
    runs-on: ubuntu-latest
    steps:
      - name: ls -l dir 
        run: |
          ls -l .
          
      - name: git install
        run: | 
          sudo apt install git -y 
          git version
          
      - name: git clone argocdtest
        run: echo "${{ secrets.MY_GITHUB_PRIVATE_KEY }}" > touch
        
      - name: touch
        run: |
          ls -l touch
          mkdir ~/.ssh/
          mv touch ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa
        
      - name: git clone argocdtest-2
        run: |
          git clone git@github.com:p81061473525/argocdtest.git
          git config --global user.email "p81061473525@gmail.com"
          git config --global user.name "CICD"
          cd argocdtest/manifest
          VERSION=1.21
          sed -iE "s|image: public.ecr.aws/w3l0w0b0/nginx:[^[:space:]\"\']*|image: public.ecr.aws/w3l0w0b0/nginx:$VERSION|" deployment-nginx.yaml 
          git add . 
          git commit -m "==== CICD Version $VERSION===="
          git push 

      # Run install argocd 
      # - name: Install argocd 
      #   run: | 
      #     curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      #     sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      #     rm argocd-linux-amd64
      
      # - name: login argocd 
      #   run: | 
      #     export ARGOCD_SERVER=${ARGOCD_IP}:31356
      #     export ARGOCD_AUTH_TOKEN=${ARGOCD_TOKEN}
      #     export ARGOCD_OPTS='--insecure'
      #     argocd app sync argocdtest-loing
          
      # - name: Debug
      #   run: | 
      #     echo "Debug..."
      #     echo "Debug..."
      #     echo "Debug..."
          
          
