name: deploy-argocd
on:
  workflow_call:
    secrets:
      MY_GITHUB_PRIVATE_KEY:
        required: true
      
jobs:
  argocd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ls -l dir 
        run: |
          ls -la .
          
      - name: source .env
        run: |
          cat .env 
          env | grep NGINX_VERSION 
          echo "================="
          source .env
          env | grep NGINX_VERSION
          
      - name: git install
        run: | 
          sudo apt install git -y 
          git version
      #--------------#
      # clone argocd #
      #--------------#
      - name: ssh key set 
        run: |
          mkdir ~/.ssh/
          echo "${{ secrets.MY_GITHUB_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 0400 ~/.ssh/id_rsa
      #--------------#
      # push  argocd #
      #--------------#        
      - name: git clone argocdtest-2
        run: |
          git clone git@github.com:p81061473525/argocdtest.git
          git config --global user.email "p81061473525@gmail.com"
          git config --global user.name "CICD"
          cd argocdtest/manifest
          sed -iE "s|image: public.ecr.aws/w3l0w0b0/nginx:[^[:space:]\"\']*|image: public.ecr.aws/w3l0w0b0/nginx:$NGINX_VERSION|" deployment-nginx.yaml 
          git add . 
          git commit -m "==== CICD Version $NGINX_VERSION===="
          git push 

      # Run install argocd 
      # - name: Install argocd 
      #   run: | 
      #     curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      #     sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      #     rm argocd-linux-amd64
      
      # - name: login argocd 
      #   run: | 
      #     export ARGOCD_SERVER=${ARGOCD_IP}:31356
      #     export ARGOCD_AUTH_TOKEN=${ARGOCD_TOKEN}
      #     export ARGOCD_OPTS='--insecure'
      #     argocd app sync argocdtest-loing
          
      # - name: Debug
      #   run: | 
      #     echo "Debug..."
      #     echo "Debug..."
      #     echo "Debug..."
          
          
