# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:
    secrets:
      AWS_ID:
        required: true
      AWS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_KEY }}
          aws-region: ap-northeast-1
              
      - name: install aws
        run: sudo apt install awscli -y 
        
      - name: install docker  
        run: sudo apt install docker -y 

      - name: check aws and docker command
        run: |
          aws --version 
          docker --version
          
      - name: systemctl restart docker 
        run: sudo systemctl restart docker 
        
      - name: dokcer build 
        run: sudo docker build -t peter_tester .

      - name: login ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w3l0w0b0

      - name: docker tag nginx_test:latest 
        run: sudo docker tag peter_tester:latest public.ecr.aws/w3l0w0b0/peter_tester:latest

      - name: docker push public.ecr.aws/w3l0w0b0/peter_tester/peter_tester:latest
        run: sudo docker push public.ecr.aws/w3l0w0b0/peter_tester:latest 
