name: BE-CI-build

on: push

env:
  RELEASE: ${{
    (startsWith(github.ref, 'refs/heads') && 'x') ||
    (startsWith(github.ref, 'refs/tags/v') && github.ref_name) ||
    'unknown'
    }}

jobs:
  Check_all_enviroment:
    # runs-on: self-hosted
    runs-on: ubuntu-latest 

    steps:
    - name: Test for ENVIRONMENT
      run: |
        echo "本次跑的參數如下"
        echo "RELEASE: ${{ env.RELEASE }}"
    - name: add file to check dockerbuild 
      run: | 
        echo "${{ env.RELEASE }}" > dockerfiletest/.emv
    - name: 顯示 dockerfiletest/.emv 
      run: |
        echo dockerfiletest/.emv
    - name: Install docker-compose
      run: |
        sudo apt install docker-compose -y 
    - name: docker images ls 
      run: | 
        sudo docker images ls 
    - name: docker build 
      run: | 
        sudo docker-compose -f dockfiletest/docker-compose.yml 
    - name: dokcer images ls again
      run: | 
        sudo docker images ls 
     
        

 
