name: BE-CI-build

on: push

env:
  RELEASE: ${{
    (startsWith(github.ref, 'refs/heads') && 'x') ||
    (startsWith(github.ref, 'refs/tags/v') && github.ref_name) ||
    'unknown'
    }}

jobs:
  Check_all_enviroment:
    # runs-on: self-hosted
    runs-on: ubuntu-latest 

    steps:
    - name: Test for ENVIRONMENT
      run: |
        echo "本次跑的參數如下"
        echo "RELEASE: ${{ env.RELEASE }}"

    - name: clone this repo.
      uses: actions/checkout@v3

    - name: add file to check dockerbuild 
      run: | 
        echo "NGINX_VERSION=${{ env.RELEASE }}" > dockerfiletest/.env
    - name: 顯示 dockerfiletest/.env 
      run: |
        cat dockerfiletest/.env
    - name: Install docker-compose
      run: |
        sudo apt install docker-compose -y 
    - name: docker images 
      run: | 
        sudo docker images
    - name: docker build 
      run: | 
        sudo docker-compose -f dockerfiletest/docker-compose.yml build
    - name: sleep 5 
      run: |
        sleep 5 
    - name: dokcer images ls again
      run: | 
        sudo docker images
     
        

 
